### ISSUE TITLE
error while running a test

### ISSUE THREAD

**Issue by asrar-khaldey** [marisacasillas/chattr-basic#15]
Hi
whenever I run a test or every other data file I keep getting this error
hope you can help
thank you
![Screenshot (311)](https://user-images.githubusercontent.com/73520777/117052749-c58f6580-ad20-11eb-9214-615208042a98.png)

**Comment by marisacasillas** [comment]
Hello! Thanks for trying out chattr. I looked through this afternoon and can't replicate your error. I realized that my test page is probably not well named. There were also some small bugs with tier names that I have now fixed.

### If you want to run tests:
- Pull the most recent version
- Open up run-tests.R (this was formerly testpage.R)
- Run the code in there
_NOTE: You won't have access to the ITS file I use so you will get a special message about those tests not being run_

### If you want to try your own input files:
- Check out the example use case [here](https://github.com/marisacasillas/chattr-basic/blob/master/CogSci2021/CogSci2021-chattr/data_prep.R)
