### ISSUE TITLE
how can one install chattr?

### ISSUE THREAD

**Issue by alecristia** [marisacasillas/chattr-basic#18]
Sorry if this is obvious! I read your Cog Sci paper & the README in this repo, and I didn't find instructions. I also tried downloading the zip:

```r
install.packages('~/Desktop/chattr-basic-master.zip')
````

That yields:

> Installing package into ‘/Users/alejandrinacristia/Dropbox/van_acq/renv/library/R-4.1/x86_64-apple-darwin17.0’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘~/Desktop/chattr-basic-master.zip’ is not available for this version of R

As well as:
`devtools::install_github("marisacasillas/chattr-basic")`, which yields:
> Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found
  Did you spell the repo owner (`marisacasillas`) and repo name (`chattr-basic`) correctly?
  If spelling is correct, check that you have the required permissions to access the repo.

Thanks in advance!

**Comment by alecristia** [comment]
ah, I think I got it. Looking at the folder with your CogSci paper, I see I can do:

```
# Load chattr code
source("../../tabularize-data.R")
source("../../transition-detectors.R")
source("../../chattr-helpers.R")
source("../../tabularize-data.R")
source("../../transition-detectors.R")
source("../../continuation-detectors.R")
source("../../intseq-detectors.R")
source("../../estimate-baseline.R")
source("../../fetch-chattr-info.R")
source("../../make-summaries.R")
```
(and adapt the path to where I put the downloaded zip).

Thanks!

**Comment by marisacasillas** [comment]
sorry for the delay @alecristia! i more recently have been experimenting with this (still somewhat horrendous) way of sourcing the myriad scripts until i get the actual package together:

```
library(devtools)
chattr.basic.url <- "https://raw.githubusercontent.com/marisacasillas/chattr-basic/master/"
source_url(paste0(chattr.basic.url, "tabularize-data.R"))
source_url(paste0(chattr.basic.url, "transition-detectors.R"))
source_url(paste0(chattr.basic.url, "chattr-helpers.R"))
source_url(paste0(chattr.basic.url, "continuation-detectors.R"))
source_url(paste0(chattr.basic.url, "intseq-detectors.R"))
source_url(paste0(chattr.basic.url, "estimate-baseline.R"))
source_url(paste0(chattr.basic.url, "fetch-chattr-info.R"))
source_url(paste0(chattr.basic.url, "make-summaries.R"))
```
